name: Check comment actor

on:
  issue_comment:
    types: [ created ]

jobs:
  print_actor:
    name: Print actor
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -X GET --header 'authorization: Bearer $GITHUB_TOKEN' 'https://api.github.com/user'
